/*
 * Decompiled with CFR 0.152.
 */
package pisi.unitedmeows.yystal;

public enum YSettings {
    TASKWORKER_FETCH_DELAY,
    TASKPOOL_CONTROL_CHECK_DELAY,
    TASK_AWAIT_DELAY,
    TCP_CLIENT_WRITE_DELAY,
    TCP_CLIENT_QUEUE_CHECK_DELAY,
    TCP_SERVER_BUFFER_SENT_DELAY,
    TCP_SERVER_BUFFER_SIZE,
    YUI_SHADER_LOCATION;

}

